// Copyright (C) 2010, Guy Barrand. All rights reserved.
// See the file tools.license for terms.

// to check all include files.

//#include <G4SystemOfUnits.hh>

#include <tools/rroot/streamer_fac>
#include <tools/rroot/tree>
#include <tools/rroot/leaf>
#include <tools/rroot/seek>
#include <tools/rroot/branch_object>
#include <tools/rroot/basket>
#include <tools/rroot/tree_index>
#include <tools/rroot/clss>
#include <tools/rroot/dummy>
#include <tools/rroot/branch>
#include <tools/rroot/ntuple>
#include <tools/rroot/branch_element>
#include <tools/rroot/base_leaf>
#include <tools/rroot/obj_list>
#include <tools/rroot/file>
#include <tools/rroot/rbuf>
#include <tools/rroot/rall>
#include <tools/rroot/fac>
#include <tools/rroot/streamers>
#include <tools/rroot/date>
#include <tools/rroot/graph>
#include <tools/rroot/THistogram>
#include <tools/rroot/stl_vector>
#include <tools/rroot/obj_array>
#include <tools/rroot/key>
#include <tools/rroot/cids>
#include <tools/rroot/directory>
#include <tools/rroot/ifile>
#include <tools/rroot/dummy_fac>
#include <tools/rroot/info>
#include <tools/rroot/object>
#include <tools/rroot/iros>
#include <tools/rroot/named>
#include <tools/rroot/iro>
#include <tools/rroot/iobject>
#include <tools/rroot/matrix>
#include <tools/rroot/vector3>
#include <tools/rroot/buffer>
#include <tools/rroot/ifac>

#include <tools/histo/base_cloud>
#include <tools/histo/p2>
#include <tools/histo/b2>
#include <tools/histo/h2>
#include <tools/histo/b3>
#include <tools/histo/axes>
#include <tools/histo/h3df>
#include <tools/histo/h3>
#include <tools/histo/c1d>
#include <tools/histo/c2d>
#include <tools/histo/h3d>
#include <tools/histo/dps>
#include <tools/histo/h1d>
#include <tools/histo/p1>
#include <tools/histo/h2d>
#include <tools/histo/h1>
#include <tools/histo/p1d>
#include <tools/histo/hmpi>
#include <tools/histo/c3d>
#include <tools/histo/axis>
#include <tools/histo/base_histo>
#include <tools/histo/b1>
#include <tools/histo/p2d>
#include <tools/histo/h1df>
#include <tools/histo/histo_data>
#include <tools/histo/profile_data>
#include <tools/histo/hd2mpi>
#include <tools/histo/h2df>

#include <tools/carray>
#include <tools/b2s>
#include <tools/num2s>
#include <tools/words>
#include <tools/hatcher>

#include <tools/lina/box3>
#include <tools/lina/geom3>
#include <tools/lina/MATCOM>
#include <tools/lina/vec3d>
#include <tools/lina/mat>
#include <tools/lina/geom2>
#include <tools/lina/box_3f>
#include <tools/lina/vec2f>
#include <tools/lina/vec3f>
#include <tools/lina/rotf>
#include <tools/lina/line>
#include <tools/lina/vec3>
#include <tools/lina/qrot>
#include <tools/lina/vec4>
#include <tools/lina/vec2>
#include <tools/lina/plane>
#include <tools/lina/box3f>
#include <tools/lina/vec4f>
#include <tools/lina/mat4>
#include <tools/lina/mat4f>
#include <tools/rcsv_ntuple>

#include <tools/zb/point>
#include <tools/zb/polygon>
#include <tools/zb/line>
#include <tools/zb/edge_table>
#include <tools/zb/buffer>

#include <tools/cstr>
#include <tools/snpf>
#include <tools/tosu>
#include <tools/wcsv_histo>
#include <tools/mathd>
#include <tools/glprims>
#include <tools/strip>
#include <tools/stype>
#include <tools/ival_func>
#include <tools/buf2lines>

//#include <tools/wroot/MPI_SET_MAX.icc>
#include <tools/wroot/tree>
#include <tools/wroot/leaf>
#include <tools/wroot/seek>
#include <tools/wroot/branch_object>
#include <tools/wroot/basket>
#include <tools/wroot/idir>
#include <tools/wroot/wbuf>
#include <tools/wroot/ibo>
#include <tools/wroot/branch>
#include <tools/wroot/ntuple>
#include <tools/wroot/branch_element>
#include <tools/wroot/base_leaf>
#include <tools/wroot/base_pntuple>
#include <tools/wroot/file>
#include <tools/wroot/mpi_send_basket>
#include <tools/wroot/streamers>
#include <tools/wroot/mt_basket_add>
#include <tools/wroot/icol>
#include <tools/wroot/itree>
#include <tools/wroot/mpi_ntuple_column_wise>
#include <tools/wroot/date>
#include <tools/wroot/bufobj>
#include <tools/wroot/mpi_create_basket>
#include <tools/wroot/base_pntuple_column_wise>
#include <tools/wroot/element>
#include <tools/wroot/mt_ntuple_column_wise>
#include <tools/wroot/key>
#include <tools/wroot/cids>
//#include <tools/wroot/columns.icc>
#include <tools/wroot/member_writer>
#include <tools/wroot/directory>
#include <tools/wroot/mt_ntuple_row_wise>
#include <tools/wroot/ifile>
#include <tools/wroot/info>
#include <tools/wroot/impi_ntuple>
#include <tools/wroot/imt_ntuple>
#include <tools/wroot/infos>
#include <tools/wroot/base_pntuple_row_wise>
#include <tools/wroot/named>
#include <tools/wroot/free_seg>
#include <tools/wroot/mpi_protocol>
#include <tools/wroot/imutex>
#include <tools/wroot/mpi_basket_add>
#include <tools/wroot/mpi_ntuple_row_wise>
#include <tools/wroot/iobject>
#include <tools/wroot/to>
#include <tools/wroot/buffer>
//#include <tools/wroot/MT_SET_MAX.icc>

#include <tools/realloc>
#include <tools/signature>
#include <tools/rtausmef>
#include <tools/get_env>
#include <tools/get_lines>
#include <tools/gl2ps_def.h>
#include <tools/cmemT>
#include <tools/file>
#include <tools/handle>

#include <tools/fileis>
#include <tools/array>
#include <tools/touplow>
#include <tools/sprintf>
#include <tools/vfind>
#include <tools/eqT>
#include <tools/rcmp>
#include <tools/safe_cast>
#include <tools/sout>
#include <tools/vmanip>
#include <tools/path>
#include <tools/snums>
#include <tools/ntuple_binding>
#include <tools/saui>
#include <tools/platform>
#include <tools/chars>
#include <tools/vdata>
#include <tools/file_format>
#include <tools/rntuple>
#include <tools/sep>
#include <tools/forit>

#include <tools/io/iwbuf>
#include <tools/io/irbuf>

#include <tools/long_out>
#include <tools/rtausmeui>
#include <tools/value>
#include <tools/raxml_out>

#include <tools/impi_world>
#include <tools/curve>
#include <tools/hplot>
#include <tools/fsize>
#include <tools/ntuple_booking>
#include <tools/gzip>
#include <tools/clist_contour>
#include <tools/nostream>
//#include <tools/hatcher.icc>
#include <tools/cids>
#include <tools/out_error>
//#include <tools/value.icc>
#include <tools/vpair>
#include <tools/mapmanip>
#include <tools/cid>

//#include <tools/xml/viewplot_fonts_google.style>
#include <tools/xml/tree>
#include <tools/xml/wrap_viewplot_fonts_google_style>
#include <tools/xml/element>
#include <tools/xml/aidas>
#include <tools/xml/styles>

#include <tools/img>
#include <tools/typedefs>
#include <tools/colorfs>
#include <tools/valop>
#include <tools/tos>
#include <tools/wps>
#include <tools/colorf>
#include <tools/S_STRING>
#include <tools/impi>

#include <tools/sg/read_action>
#include <tools/sg/tex_rect>
#include <tools/sg/f2plot>
#include <tools/sg/infos_box>
#include <tools/sg/legend>
#include <tools/sg/style_colormap>
#include <tools/sg/fit2plot>
#include <tools/sg/vertices>
#include <tools/sg/strings>
#include <tools/sg/tools>
#include <tools/sg/render_manager>
#include <tools/sg/mf>
#include <tools/sg/ifield_factory>
#include <tools/sg/pick_action>
#include <tools/sg/sf_rotf>
#include <tools/sg/markers>
#include <tools/sg/base_tex>
#include <tools/sg/valop2sg>
#include <tools/sg/cbks>
#include <tools/sg/cloud2plot>
#include <tools/sg/node_desc>
#include <tools/sg/group>
#include <tools/sg/primitive_visitor>
#include <tools/sg/gstos>
#include <tools/sg/plottable>
#include <tools/sg/back_area>
#include <tools/sg/separator>
#include <tools/sg/bmf>
#include <tools/sg/bcbk>
#include <tools/sg/path>
#include <tools/sg/cube>
#include <tools/sg/event_dispatcher>
#include <tools/sg/gstos_add>
#include <tools/sg/zb_action>
#include <tools/sg/torche>
#include <tools/sg/gl2ps_action>
#include <tools/sg/rgba>
#include <tools/sg/enums>
#include <tools/sg/plotter_style>
#include <tools/sg/sf_img>
#include <tools/sg/bbox_action>
#include <tools/sg/text_valop>
#include <tools/sg/style>
#include <tools/sg/cloud2plot_cp>
#include <tools/sg/state>
#include <tools/sg/lpat>
#include <tools/sg/gl2ps_manager>
#include <tools/sg/field>
#include <tools/sg/_switch>
#include <tools/sg/dummy_freetype>
#include <tools/sg/sf_string>
#include <tools/sg/text_hershey_marker>
#include <tools/sg/sf_vec>
#include <tools/sg/tex_quadrilateral>
#include <tools/sg/event_action>
#include <tools/sg/write_paper>
#include <tools/sg/get_matrix_action>
#include <tools/sg/search>
#include <tools/sg/text_style>
#include <tools/sg/plotter_some_styles>
#include <tools/sg/blend>
#include <tools/sg/text_hershey>
#include <tools/sg/render_gstos>
#include <tools/sg/holder>
#include <tools/sg/sf>
#include <tools/sg/device_interactor>
#include <tools/sg/action>
#include <tools/sg/viewer>
#include <tools/sg/rep>
#include <tools/sg/ecbk>
#include <tools/sg/write_action>
#include <tools/sg/axis>
#include <tools/sg/states>
#include <tools/sg/head_light>
#include <tools/sg/sf_vec3f>
#include <tools/sg/noderef>
#include <tools/sg/normal>
#include <tools/sg/plots_viewer>
#include <tools/sg/visible_action>
#include <tools/sg/zb_manager>
#include <tools/sg/senums>
#include <tools/sg/keys>
#include <tools/sg/nodekit>
#include <tools/sg/draw_style>
#include <tools/sg/ellipse>
#include <tools/sg/base_freetype>
#include <tools/sg/text>
#include <tools/sg/sf_mat4f>
#include <tools/sg/node>
#include <tools/sg/cursor_shape>
#include <tools/sg/atb_vertices>
#include <tools/sg/line_style>
#include <tools/sg/h2plot>
#include <tools/sg/ortho>
#include <tools/sg/colormap>
#include <tools/sg/plotter>
#include <tools/sg/style_parser>
#include <tools/sg/sf_vec4f>
#include <tools/sg/render_action>
#include <tools/sg/senum>
#include <tools/sg/h2plot_cp>
#include <tools/sg/style_color>
#include <tools/sg/base_camera>
#include <tools/sg/event>
#include <tools/sg/matrix>
#include <tools/sg/xy2plot>
#include <tools/sg/base_text>
#include <tools/sg/win_action>
#include <tools/sg/perspective>
#include <tools/sg/field_desc>
#include <tools/sg/bsf>
#include <tools/sg/sf_enum>
#include <tools/sg/mnmx>
#include <tools/sg/plots>
#include <tools/sg/search_action>
#include <tools/sg/matrix_action>
#include <tools/sg/light_off>
#include <tools/sg/plottables>

#include <tools/version>
#include <tools/colors>
#include <tools/schar>
#include <tools/ccontour>
#include <tools/s2time>
#include <tools/hls>
#include <tools/spline>
#include <tools/hershey>
#include <tools/argcv>
#include <tools/mathf>

#include <tools/sbeg>
//#include <tools/plotter_common.icc>
#include <tools/press_func>
#include <tools/smath>
#include <tools/columns>
#include <tools/data_axis>

#include <tools/font/lato_regular_ttf>
#include <tools/font/lato_license>
#include <tools/font/roboto_bold_ttf>
#include <tools/font/roboto_license>

#include <tools/charmanip>

#include <tools/pointer>
#include <tools/args>
#include <tools/viewplot>

#include <tools/waxml/ntuple>
#include <tools/waxml/begend>
#include <tools/waxml/histos>
#include <tools/smatch>

#include <tools/glutess/mesh>
#include <tools/glutess/_tess>
#include <tools/glutess/priorityq>
#include <tools/glutess/license>
#include <tools/glutess/tessmono>
#include <tools/glutess/render>
#include <tools/glutess/memalloc>
#include <tools/glutess/geom>
#include <tools/glutess/sweep>
#include <tools/glutess/normal>
#include <tools/glutess/_glu>
#include <tools/glutess/rename>
#include <tools/glutess/glutess>
#include <tools/glutess/dict>
#include <tools/glutess/undef>

#include <tools/gl2ps>
#include <tools/aida_ntuple>
#include <tools/tokenize>
#include <tools/file_reader>
#include <tools/charp_out>
#include <tools/HEADER>
#include <tools/rcsv_histo>
#include <tools/sto>
#include <tools/mnmx>
#include <tools/tess_contour>
#include <tools/srep>
#include <tools/mem>

#include <tools/store/iobj_visitor>
#include <tools/store/iobj_const_visitor>
#include <tools/store/osc_streamers>

#include <tools/scast>
#include <tools/fmanip>
#include <tools/wcsv_ntuple>

//toolx:
#include <toolx/xml/loader>
#include <toolx/xml/xml_style>
#include <toolx/zlib>
#include <toolx/raxml>

#include <toolx/sg/text_freetype>
#include <toolx/sg/text_freetype_marker>

#include <toolx/hdf5/tools>
#include <toolx/hdf5/ntuple>
#include <toolx/hdf5/T_tools>
#include <toolx/hdf5/hdf5_h>
#include <toolx/hdf5/group_exists>
#include <toolx/hdf5/atb>
#include <toolx/hdf5/h2file>
#include <toolx/hdf5/pages>
#include <toolx/hdf5/header>
#include <toolx/hdf5/store>

#include <toolx/OpenGL>
#include <toolx/sg/GL_action>
#include <toolx/sg/GL_viewer>
#include <toolx/sg/GL_manager>
#include <toolx/sg/gl>
#include <toolx/glbuf>

#include <toolx/mpi/wait_buffer>
#include <toolx/mpi/world>
#include <toolx/mpi/hmpi>
#include <toolx/mpi/wrmpi>

#ifdef _MSC_VER
#include <toolx/Windows/window>
#include <toolx/Windows/sg_viewer>
#include <toolx/Windows/glarea>
#include <toolx/Windows/session>

#include <toolx/Qt/sg_viewer>
#include <toolx/Qt/glarea>
#include <toolx/Qt/session>
#else
#include <toolx/X11/dispatcher>
#include <toolx/X11/base_session>
#include <toolx/X11/simple_dispatcher>
#include <toolx/X11/sg_viewer>
#include <toolx/X11/session>

#include <toolx/Xt/OpenGLArea>
#include <toolx/Xt/sg_viewer>
#include <toolx/Xt/session>

/*
#include <toolx/Qt/sg_viewer>
#include <toolx/Qt/glarea>
#include <toolx/Qt/session>
*/
#endif

int main(int,char**) {return 0;}
